### ISSUE TITLE
Emit *:typing messages

### ISSUE THREAD

**Issue by mihok** [minimalchat/daemon#21]
We want to enable the client or operator to see when someone is working on a message to us. To do this, we need the Operator to emit `operator:typing` on keyDown, we really dont need much more information than that since we can use that as a 'ping' to send to the client.

On the client side, similarly, we need to emit an `client:typing` event on keyDown as well. 

Then on the daemon side, we'll need to pass these messages through just like the `client:message` and `operator:message` events. Files in the daemon to focus on:

- `server/socket/server.go`

**Comment by mihok** [comment]
This is a good ticket for either of you @teesloane, @broneks. (Or even pair programming it!)

**Comment by teesloane** [comment]
Sounds good. Excited to get into this. If you can assign more go-lang issues i'd be super down to look into that

**Comment by broneks** [comment]
@mihok Tees and I worked on this feature together. However it seems like any go code that we add does not get compiled/ran (not even Println in the main function). I tried all the different makefile scripts and nothing works. What are we doing wrong?

**Comment by broneks** [comment]
we are running daemon locally of course.

**Comment by mihok** [comment]
What does `make run` do?

**Comment by broneks** [comment]
`run: lint test go`
...
`go:`
`      cd $(SRC)`
`	$(GO_CMD) run main.go`

**Comment by broneks** [comment]
ahhhhh I just realized I have to two repos `mnml-daemon` and `daemon`

**Comment by broneks** [comment]
derp :poop:

**Comment by mihok** [comment]
This is done in #28
